### PR TITLE
Interactive Dropdown for food image

### PR DESCRIPTION
**Pull request by Vedaant-Mahale**
A dropdown with the info of the food you clicked at will appear below the image. to perform this, the arrangement of the images have also been changed. however if anyone can create an animation for this without affecting the div sizes it would be much appreciated.

### CODE REVIEW

**Comment by techcsispit** [comment]
Resolve the merge conflicts in this pr

**Comment by Vedaant-Mahale** [comment]
Conflicts resolved

**Comment by techcsispit** [comment]
Can you provide some screencshots of your the website before and after the changes you made

**Comment by Vedaant-Mahale** [comment]
https://youtu.be/lgpxeOdtNLM please use this link to access the full video, screenshots wouldnt be useful to showcase animations

**Pull request merged**
