### PR TITLE
Modify and Enhance Dark Mode Feature

### PR DESCRIPTION
**Pull request by caPt-tanmAY11**
The Dark Mode feature of the website was not user interactive as in this mode, the logo and the icons of social media links in the top navigation bar were not visible.
They get highlighted only when the user hovers over the bar randomly.

Also, the webpage was not visually appealing as it is completely black.

Hence, modified and enhanced the Dark Mode feature.

### CODE REVIEW

**Comment by caPt-tanmAY11** [comment]
Also,
Kindly find the attached screenshots of the changes for your reference.

1) 
Mainpage (BEFORE) :
mainpage_Before

Mainpage (AFTER) :
mainpage_After


2)
ContactUs page (BEFORE) :
contactuspage_Before

ContactUs page (AFTER) :
contactuspage_After

**Comment by techcsispit** [comment]
Can the color scheme be entirely changed both for dark mode as well as light mode

**Comment by caPt-tanmAY11** [comment]
Yes, sure
Will make the required changes.

**Comment by caPt-tanmAY11** [comment]
Changed the colour scheme and font for the light mode and dark mode of website

**Comment by caPt-tanmAY11** [comment]
Changed the colour scheme and font for the light mode and dark mode of website

**Comment by caPt-tanmAY11** [comment]
Kindly find the attached screenshots of the changes for your reference.

1) Main page-
mainpage_After


2) Contact page-
contactpage_After


3) In Dark Mode-
contactpage_DarkM_After

**Comment by techcsispit** [comment]
Looks impressive!!!!

**Comment by caPt-tanmAY11** [comment]
Thank you!!

**Pull request merged**
