### PR TITLE
Contact Us Section Feature Enhancement

### PR DESCRIPTION
**Pull request by caPt-tanmAY11**
Modified and enhanced the Contact Us section of the index.html file.

### CODE REVIEW

**Comment by techcsispit** [comment]
Please provide more detailed information with some screenshots of the changes you provided.

**Comment by caPt-tanmAY11** [comment]
Yes,
Please find the attached changes in the before and after images-

before
after

**Comment by caPt-tanmAY11** [comment]
Hello,
Could you please let me know if any additional changes are needed here, or if this is acceptable? 
If required, I will improve this section, but if it’s fine as is, I can focus on other areas of the website.

**Comment by techcsispit** [comment]
Seems good I will merge this for now if you are working on some other part of website please raise a issue  and also try to improve its design even more in the future

**Comment by caPt-tanmAY11** [comment]
Okayy,
Thank you!

**Pull request merged**
